### ISSUE TITLE
-v or --version args does not print the version

### ISSUE THREAD

**Issue by Panthro** [AdaptiveMe/adaptive-tools-nibble#10]
Just updated nibble using npm, and wanted to check the version, but the -v switch prints nothing

with the npm nibble command 

```
$ nibble -v
[nibble] Running Adaptive Nibble...
```

With the nibble binary

```
$ ./adaptive-nibble-emulator -v
```

Same thing with --version

**Comment by carloslozano** [comment]
Fixed in release 1.0.alpha7
